# file: roles/nginx/tasks/package.yml

- name: Nginx | Add the nginx repo to the apt sources
  apt_repository: repo='ppa:nginx/stable'

- include: commons.yml

- name: Nginx | Make sure nginx is installed
  apt: pkg=nginx
  notify:
    - restart nginx
