# file: roles/nginx/tasks/user.yml

- name: make sure the nginx group is present
  group: >
    name={{nginx_group}}
    state=present

- name: make sure the www directory is present
  file: >
    path={{nginx_www_dir}}
    state=directory

- name: make sure the nginx user is present
  user: >
    name={{nginx_user}}
    group={{nginx_group}}
    state=present

- name: set the right directory permissions for the www directory
  file: >
    path={{nginx_www_dir}}
    owner={{nginx_user}}
    group={{nginx_group}}
    mode=0755
    state=directory

- name: set the right expiration on the nginx user
  command: "sudo chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 {{nginx_user}}"
